months=set(["january","feburary","march","april","may","june"])
print("the original set")
print(months)
print("adding other months to the set")
months.add("july")
months.add("august")
print(months)
print("printing modified set")
print(months)
